config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'articles#index'
  resources :sessions, only: %w[index create destroy]
  resources :categories, only: %[show] 
  resources :articles do
    resource :vote, only: %w[create destroy]
  end
  resources :users
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :category
  has_many :votes
  validates :title, presence: true
  validates :text, presence: true
  has_one_attached :image

  def self.top_article
    return unless Vote.any?

    article_id = Vote.group(:article_id).count.max_by { |_, v| v }.first
    Article.find(article_id)
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[show edit update destroy]
  before_action :set_current_user

  def index
    @articles = Article.all
    @top = Article.top_article
    @categories = Category.order(:priority).limit(4).includes(:articles)
  end

  def show; end

  def new
    @article = Article.new
  end

  def edit
    unless @current_user == @article.author
      redirect_to article_path, notice: 'Seems like this article does not belong to you!'
    end

    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :text, :category_id, :image).merge(author_id: @current_user.id)
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def top_title(article)
    article.try(:title)
  end

  def top_image(article)
    url_for(article.try(:image).blob)
  end

  def top_content(article)
    article.try { |a| a.text.truncate(100, separator: ' ', omission: '... Read more') }
  end

  def number_of_votes(article)
    pluralize(article.votes.size, 'vote')
  end

  def author_name(article)
    article.user.name
  end

  def latest_article_cover(category)
    return if category.try(:articles).nil?

    img_blob = category.articles.last.image.blob
    url_for(img_blob)
  end

  def top_title_link(article)
    link_to(top_title(article), article_path(article), class: 'simple-link top-title m-2 p-2') if article
  end
end

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %><br/>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :text %><br/>
    <%= form.text_area :text %>
  </div>

  <div class="field my-3">
    <%= form.file_field :image %>
  </div>

  <div class="field">
    <%= form.label :category_id, 'Category' %>
    <%= form.collection_select :category_id, Category.order(:name), :id, :name %>
  </div>

  <div class="actions my-3">
    <%= form.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/articles/_votes.html.erb
<%= vote_button(@article) if @current_user %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<main class="landing-page mt-0 pt-0">
  <p id="notice" class="p-0 m-0"><%= notice %></p>
  <div class="top" style="background-image: linear-gradient(rgba(232, 199, 192,.2), rgba(232, 199, 192,.2)), url(<%= top_image(@top) %>);">
    <div class="pt-2">
      <%= top_title_link(@top) %>
    </div>
    <p class="top-text m-3 p-3"><%= top_content(@top) %></p>
  </div>

  <div class="landing-grid">
    <% @categories.each do |category| %>
      <div class='category-articles'
            style="background-image: linear-gradient(rgba(232, 199, 192,.1), rgba(232, 199, 192,.1)), url(<%= latest_article_cover(category) %>);">
        <div class="d-flex flex-column">
          <%= link_to category.name, category_path(category), class:'category-style pt-2 simple-link text-uppercase' %>
          <span><%= article_by_category(category) %></span>
        </div>
      </div>
    <% end %>
  </div>
</main>

app/views/articles/new.html.erb
<div class="container">
  <h1 class="article-title">New Article</h1>
  <%= render 'form', article: @article %>

  <%= link_to 'Back', articles_path %>
</div>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <div class="d-flex flex-column">
    <%= content_tag :h2, @article.title, class: 'article-title' %>

    <%= render partial: "votes" %>

    <% if @article.image.attached? %>
      <%= image_tag url_for(@article.image), width:'300px' %>
    <% end %>

    <div class="d-flex flex-column">
      <%= content_tag :p, markdown(@article.text), class: 'article-text' %>
    </div>

    <% if @current_user == @article.author %>
      <%= link_to 'Edit', edit_article_path(@article) %>
    <% end %>
    <%= link_to 'Back', articles_path %>
  </div>
</div